---
# network
host: '0.0.0.0'
port: 5566

# map
map_file: './data/maps/map_complex_1cm.png'
map_scale: 0.01

# display
robot_radius: 10

# simulation
start_pose:
  x: 1.0
  y: 1.0
  z: 0.0
use_noisy_pose: off
robot_phy_length: 0.32
position_noise_stddev: 0.05

# localization proxy
proxy_real_robot: off
proxy_host: 'localhost'
proxy_port: 5567

# logging
log_level: 'debug'

# clues
clues:
  - clue_id: 1
    trigger:
      x: 1.0
      y: 1.0
      r: 0.5
    location:
      x: 6.8
      y: 4.8
    audio_file: './data/audio/evala_00001.wav'
  - clue_id: 2
    trigger:
      x: 1.0
      y: 1.0
      r: 0.5
    location:
      x: 6.0
      y: 4.5
    audio_file: './data/audio/evala_00001.wav'
  - clue_id: 3
    trigger:
      x: 1.0
      y: 1.0
      r: 0.5
    location:
      x: 6.5
      y: 4.5
    audio_file: './data/audio/evala_00001.wav'
  - clue_id: 4
    trigger:
      x: 1.0
      y: 1.0
      r: 0.5
    location:
      x: 3.5
      y: 1.0
    audio_file: './data/audio/evala_00001.wav'
  - clue_id: 5
    trigger:
      x: 1.0
      y: 1.0
      r: 0.5
    location:
      x: 4.0
      y: 4.0
    audio_file: './data/audio/evala_00001.wav'


# targets
targets:
  - target_id: 1
    trigger:
      x: 6.8
      y: 4.8
      r: 0.2
    image_file: './data/imgs/image_0000.png'
targets:
  - target_id: 2
    trigger:
      x: 6.0
      y: 4.5
      r: 0.2
    image_file: './data/imgs/image_0000.png'
targets:
  - target_id: 3
    trigger:
      x: 6.5
      y: 4.5
      r: 0.2
    image_file: './data/imgs/image_0000.png'
targets:
  - target_id: 4
    trigger:
      x: 3.5
      y: 1.0
      r: 0.2
    image_file: './data/imgs/image_0000.png'
targets:
  - target_id: 5
    trigger:
      x: 4.0
      y: 4.0
      r: 0.2
    image_file: './data/imgs/image_0000.png'